APP_NAME=Laravel
APP_ENV=production
APP_KEY=base64:RbDsNPnY54sytQdc6usERUEO52fNtdUW3Q2YbqESUxA=
APP_DEBUG=false
APP_PS=Maxtech2018
APP_URL=https://forms.beamconl.com

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=database
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=beamcoforms@beamconl.com
MAIL_PASSWORD=beamcoforms@beamconl.com
MAIL_ENCRYPTION=TLS

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

